export const storeLocationsDropdown = {
  'San Diego (Miramar)': {
    Monday: { from: 10, to: 19, closed: false },
    Tuesday: { from: 10, to: 19, closed: false },
    Wednesday: { from: 10, to: 19, closed: false },
    Thursday: { from: 20, to: 19, closed: false },
    Friday: { from: 10, to: 19, closed: false },
    Saturday: { from: 10, to: 17, closed: false },
    Sunday: { closed: true },
    selected: false,
  },
  'El Cajon': {
    Monday: { from: 9, to: 19, closed: false },
    Tuesday: { from: 9, to: 19, closed: false },
    Wednesday: { from: 9, to: 19, closed: false },
    Thursday: { from: 9, to: 19, closed: false },
    Friday: { from: 9, to: 19, closed: false },
    Saturday: { from: 10, to: 19, closed: false },
    Sunday: { from: 11, to: 17, closed: false },
    selected: false,
  },
  'Mission Valley': {
    Monday: { from: 9, to: 19, closed: false },
    Tuesday: { from: 9, to: 19, closed: false },
    Wednesday: { from: 9, to: 19, closed: false },
    Thursday: { from: 9, to: 19, closed: false },
    Friday: { from: 9, to: 19, closed: false },
    Saturday: { from: 10, to: 19, closed: false },
    Sunday: { from: 11, to: 17, closed: false },
    selected: false,
  },
  'Santee': {
    Monday: { from: 9, to: 19, closed: false },
    Tuesday: { from: 9, to: 19, closed: false },
    Wednesday: { from: 9, to: 19, closed: false },
    Thursday: { from: 9, to: 19, closed: false },
    Friday: { from: 9, to: 19, closed: false },
    Saturday: { from: 10, to: 19, closed: false },
    Sunday: { from: 11, to: 16, closed: true },
    selected: false,
  },
  'Encinitas': {
    Monday: { from: 10, to: 17, closed: false },
    Tuesday: { from: 10, to: 17, closed: false },
    Wednesday: { from: 10, to: 17, closed: false },
    Thursday: { from: 10, to: 17, closed: false },
    Friday: { from: 10, to: 17, closed: false },
    Saturday: { from: 10, to: 3, closed: false },
    Sunday: { closed: true },
    selected: false,
  },
  'Carlsbad': {
    Monday: { from: 10, to: 18, closed: false },
    Tuesday: { from: 10, to: 18, closed: false },
    Wednesday: { from: 10, to: 18, closed: false },
    Thursday: { from: 10, to: 18, closed: false },
    Friday: { from: 10, to: 18, closed: false },
    Saturday: { from: 10, to: 3, closed: false },
    Sunday: { closed: true },
    selected: false,
  },
  'Oceanside': {
    Monday: { from: 10, to: 20, closed: false },
    Tuesday: { from: 10, to: 20, closed: false },
    Wednesday: { from: 10, to: 20, closed: false },
    Thursday: { from: 10, to: 20, closed: false },
    Friday: { from: 10, to: 20, closed: false },
    Saturday: { from: 10, to: 20, closed: false },
    Sunday: { from: 10, to: 20, closed: true },
    selected: false,
  },
  'Mobile Service': {
    Monday: { from: 9, to: 19, closed: false },
    Tuesday: { from: 9, to: 19, closed: false },
    Wednesday: { from: 9, to: 19, closed: false },
    Thursday: { from: 9, to: 19, closed: false },
    Friday: { from: 10, to: 19, closed: false },
    Saturday: { from: 10, to: 17, closed: false },
    Sunday: { closed: true },
    selected: false,
  },
};
